r"""Compose ``docs/assets/social-preview.png`` from the committed UI capture.

Run ``pip install -e \".[docs]\" && playwright install chromium`` once, then
``python scripts/make_social_preview.py``.

The image is laid out in HTML and screenshotted, rather than drawn by an image
library or generated by a model. Three reasons: the wordmark is real text, so it
is exactly right rather than approximately right; the palette is read from the
same tokens as the running UI, so the card cannot drift away from the product it
advertises; and the evidence panel is the committed grounded capture itself, not
a re-staged imitation of it.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"
SOURCE = ASSETS / "ui-grounded.png"
OUTPUT = ASSETS / "social-preview.png"
STYLESHEET = ROOT / "src" / "production_rag" / "static" / "app.css"
# GitHub renders a social preview at 1280x640 and crops anything taller, so the
# card is built at exactly that size rather than at a 16:9 ratio that would lose
# a band off the top and bottom.
WIDTH = 1280
HEIGHT = 640
WORDMARK = "production-rag"
TAGLINE = "free path"

TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
* {{ box-sizing: border-box; margin: 0; }}
body {{
  width: {width}px; height: {height}px; overflow: hidden;
  display: grid; grid-template-columns: 1fr 1fr; align-items: center; gap: 3rem;
  padding: 3.6rem 3.6rem 3.6rem 4.4rem;
  color: {ink}; background: radial-gradient(circle at 78% -10%, #18362c 0, #09110f 40rem);
  font: 16px/1.5 system-ui, sans-serif;
}}
.eyebrow {{
  color: {green}; font-size: .82rem; font-weight: 750;
  letter-spacing: .16em; text-transform: uppercase;
}}
h1 {{ margin: .5rem 0 0; font-size: 4.1rem; line-height: .95; letter-spacing: -.055em; }}
h1 .path {{ color: {green}; }}
.lede {{ margin-top: 1.1rem; color: {muted}; font-size: 1.32rem; line-height: 1.35; }}
.chips {{ display: flex; flex-wrap: wrap; gap: .5rem; margin-top: 1.7rem; }}
.chip {{
  padding: .42rem .85rem; border: 1px solid {line}; border-radius: 999px;
  background: {panel}; color: {muted}; font-size: .88rem; font-weight: 600;
}}
.chip.lead {{ border-left: 4px solid {green}; color: {green}; letter-spacing: .04em; }}
figure {{
  position: relative; height: 100%; border: 1px solid {line}; border-radius: 18px;
  background: {sunk}; overflow: hidden;
}}
figure img {{ display: block; width: 100%; }}
figure::after {{
  content: ""; position: absolute; inset: auto 0 0 0; height: 45%;
  background: linear-gradient(to bottom, transparent, #09110f);
}}
</style></head><body>
<section>
  <p class="eyebrow">Evidence first &middot; offline capable</p>
  <h1>{wordmark}<br><span class="path">{tagline}</span></h1>
  <p class="lede">Hybrid retrieval, resolvable citations, and refusal when the
  evidence is absent.</p>
  <div class="chips">
    <span class="chip lead">$0 &middot; no API key</span>
    <span class="chip">dense + sparse &rarr; RRF</span>
    <span class="chip">offline evals</span>
  </div>
</section>
<figure><img src="data:image/png;base64,{capture}" alt=""></figure>
</body></html>
"""


def _palette() -> dict[str, str]:
    """Read the card's colours from the UI stylesheet instead of restating them."""
    root = STYLESHEET.read_text(encoding="utf-8").split("}", 1)[0]
    tokens = dict(re.findall(r"--([a-z]+):\s*(#[0-9a-fA-F]{3,8})", root))
    missing = {"ink", "muted", "panel", "line", "sunk", "green"} - tokens.keys()
    if missing:
        raise RuntimeError(f"app.css no longer defines: {', '.join(sorted(missing))}")
    return tokens


def _document() -> str:
    if not SOURCE.exists():
        raise RuntimeError(f"the grounded capture is missing: {SOURCE.relative_to(ROOT)}")
    return TEMPLATE.format(
        width=WIDTH,
        height=HEIGHT,
        wordmark=WORDMARK,
        tagline=TAGLINE,
        capture=base64.b64encode(SOURCE.read_bytes()).decode("ascii"),
        **_palette(),
    )


def compose(output: Path) -> None:
    """Render the card and write it to ``output``."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:
        raise RuntimeError(
            'Playwright is documentation-only; install it with pip install -e ".[docs]"'
        ) from exc

    ASSETS.mkdir(parents=True, exist_ok=True)
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        page = browser.new_page(
            viewport={"width": WIDTH, "height": HEIGHT}, device_scale_factor=1
        )
        page.set_content(_document(), wait_until="load")
        page.screenshot(path=output, animations="disabled", caret="hide")
        browser.close()

    data = output.read_bytes()
    print(
        f"{output.relative_to(ROOT)}: {WIDTH}x{HEIGHT}  "
        f"{len(data) / 1_000:.0f} kB  sha256 {hashlib.sha256(data).hexdigest()}"
    )


def main() -> int:
    """Parse CLI arguments and return a process exit code."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT, help="destination PNG")
    args = parser.parse_args()
    try:
        compose(args.output)
    except RuntimeError as exc:
        print(f"social preview failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
